---
- hosts: localhost
  connection: local
  vars:
    vim_dir: "{{ home_dir }}/.vim"
    vimrc: "{{ home_dir }}/.vimrc"
  tasks:
    - name: Check if vim is installed
      package:
        name: vim
        state: present

    - name: Ensure .vim/autoload directory exists
      file:
        path: "{{ item }}"
        state: directory
        recurse: no
        mode: 0750
      loop:
        - "{{ vim_dir }}"
        - "{{ vim_dir }}/autoload"

    - name: Configure vimrc
      copy:
        src: files/vimrc
        dest: "{{ vimrc }}"
        mode: 0640

    - name: Check if vim-plug is installed
      stat:
        path: "{{ vim_dir }}/autoload/plug.vim"
      register: vimplug_exists
      changed_when: not vimplug_exists.stat.exists
      notify: get_vimplug

    - name: Install vim plugins
      command: "vim -esu {{ vimrc }} +PlugUpgrade +qa || true && vim -esu {{ vimrc }} +PlugClean! +qa || true && vim -esu {{ vimrc }} +PlugUpdate +qa || true"
      args:
        creates: "{{ vim_dir }}/plugged"

  handlers:
    - name: get_vimplug
      ansible.builtin.get_url:
        url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
        dest: "{{ vim_dir }}/autoload/plug.vim"
        mode: 0640
