writeable = yes
valid users = {{ main_user_account }}, {{ share_user_account }}
create mask = 0664
directory mask = 2775
force group = mc
inherit permissions = yes
inherit acls = yes
force create mode = 0664
force directory mode = 2775

