# File managed by Ansible - https://github.com/pedbarbosa/ansible

# Adjusting zsh typeset
typeset -F SECONDS
typeset -U path

zsh_timer_00_start=$SECONDS

# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block, everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi
zsh_timer_01_powerlevel=$SECONDS

# Load and configure oh-my-zsh
export ZSH=$HOME/.oh-my-zsh
ZSH_THEME="powerlevel10k/powerlevel10k"
DISABLE_AUTO_UPDATE="true"
COMPLETION_WAITING_DOTS="true"
HIST_STAMPS="yyyy-mm-dd"
plugins=(command-not-found cp docker docker-compose git gitfast pip rsync sudo)
source ${ZSH}/oh-my-zsh.sh
zsh_timer_02_ohmyzsh=$SECONDS

# Initialise zsh completion and add 'zsh-completions' if available
if [[ -x /usr/local/share/zsh-completions ]]; then
    fpath=(/usr/local/share/zsh-completions ${fpath})
fi
compinit
zsh_timer_03_compinit=$SECONDS

# Turn on fuzzy matching
source ~/.fzf.zsh
zsh_timer_04_fzf=$SECONDS

# Set up rbenv
export PATH="$HOME/.rbenv/bin:$PATH"
eval "$(rbenv init -)"
zsh_timer_05_rbenv=$SECONDS

# Set up pyenv
if [[ -d "$HOME/.pyenv" ]]; then
    PATH="$HOME/.pyenv/bin:$PATH"
    eval "$(pyenv init -)"
    eval "$(pyenv virtualenv-init -)"
fi
zsh_timer_06_pyenv=$SECONDS

# Set up command-not-found
if brew command command-not-found-init > /dev/null 2>&1; then eval "$(brew command-not-found-init)"; fi
zsh_timer_07_command_not_found=$SECONDS

# Path and extra aliases
export PATH="$PATH:$HOME/bin"
if [[ -f ~/.zshrc_aliases ]]; then
    source ~/.zshrc_aliases
fi
zsh_timer_08_aliases=$SECONDS

autoload -U +X bashcompinit && bashcompinit
zsh_timer_09_autocomplete=$SECONDS

# Tilix VTE configuration
if [ $TILIX_ID ] || [ $VTE_VERSION ]; then
        source /etc/profile.d/vte.sh
fi
zsh_timer_10_tilix=$SECONDS

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh
zsh_timer_11_finish=$SECONDS

