# File managed by Ansible - https://github.com/pedbarbosa/ansible

# Adjusting zsh typeset
typeset -F SECONDS
typeset -U path

zsh_timer_counter=1
zsh_timer() {
  export zsh_timer_$(printf "%02d" zsh_timer_counter)_$1=$SECONDS
  ((zsh_timer_counter++))
}
zsh_timer start

# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block, everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi
zsh_timer powerlevel

# Set up pyenv before OMZ
if [[ -d "$HOME/.pyenv" ]]; then
  export PYENV_ROOT="$HOME/.pyenv"
  export PATH="$PYENV_ROOT/bin:$PATH"
  eval "$(pyenv init --path)"
  zsh_timer pyenv
fi

# Load and configure oh-my-zsh
export ZSH=$HOME/.oh-my-zsh
ZSH_THEME="powerlevel10k/powerlevel10k"
DISABLE_AUTO_UPDATE="true"
COMPLETION_WAITING_DOTS="true"
HIST_STAMPS="yyyy-mm-dd"
plugins=(command-not-found cp docker docker-compose git gitfast pip rsync sudo)
source ${ZSH}/oh-my-zsh.sh
zsh_timer ohmyzsh

# Initialise zsh completion and add 'zsh-completions' if available
if [[ -x /usr/local/share/zsh-completions ]]; then
    fpath=(/usr/local/share/zsh-completions ${fpath})
fi
compinit
zsh_timer compinit

# Turn on fuzzy matching
if [[ -f "$HOME/.fzf.zsh" ]]; then
    source "$HOME/.fzf.zsh"
    zsh_timer fzf
fi

# Set up rbenv
if [[ -d "$HOME/.rbenv" ]]; then
    export RBENV_ROOT=~/.rbenv
    eval "$(rbenv init -)"
    zsh_timer rbenv
fi


# Path and extra aliases
export PATH="$PATH:$HOME/bin"
zsh_timer path

autoload -U +X bashcompinit && bashcompinit
zsh_timer autocomplete

# Tilix VTE configuration
if [ $TILIX_ID ] || [ $VTE_VERSION ]; then
        source /etc/profile.d/vte.sh
fi
zsh_timer tilix

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh
zsh_timer p10k

zsh_timer end
unset zsh_timer_counter
