---
- hosts: all
  become: yes
  become_user: root
  tasks:
  - name: ubuntu - Set apt base sources
    copy:
      src: files/sources.list_jammy
      dest: /etc/apt/sources.list
      owner: root
      group: root
      mode: 0664
  - name: ubuntu - Check if base packages are installed
    apt:
      name: bash-completion, curl, ethtool, git, iftop, iotop, lsof, meld, mlocate, ncdu, net-tools, openssh-server, rsync, ruby, wget
      state: present
      update_cache: true
  - name: bash - Update bashrc
    copy:
      src: files/bash.bashrc
      dest: /etc/bash.bashrc
      owner: root
      group: root
      mode: 0644
  - name: sshd - Configure service
    copy:
      src: files/sshd_config
      dest: /etc/ssh/sshd_config
      owner: root
      group: root
      mode: 0644
    notify: Restart sshd
  - name: Configure sysctl.conf
    copy:
      src: files/sysctl.conf
      dest: /etc/sysctl.conf
      owner: root
      group: root
      mode: 0644
    notify: Reload sysctl
  handlers:
  - name: Restart sshd
    service:
      name: sshd
      state: restarted
  - name: Reload sysctl
    become: yes
    command: sysctl -p
