---
- hosts: all
  become: yes
  become_user: root
  tasks:
    - name: docker - package requirements
      apt:
        name: ca-certificates, curl
        state: latest
        update_cache: yes

    - name: docker - Check that keyrings folder exists
      file:
        path: /etc/apt/keyrings
        state: directory
        mode: 0755

    - name: docker - Add GPG apt key
      ansible.builtin.get_url: 
        url: https://download.docker.com/linux/ubuntu/gpg
        dest: /etc/apt/keyrings/docker.asc
        mode: 0644

    - name: docker - Add repository
      apt_repository:
        repo: "deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu {{ ansible_lsb.codename }} stable"
        state: present

    - name: docker - install packages
      apt:
        name: docker-ce, docker-ce-cli, containerd.io, docker-buildx-plugin, docker-compose-plugin, python3-docker
        state: latest
        update_cache: yes
