---
- hosts: all
  become: yes
  become_user: root
  tasks:
  - name: Check if hddtemp is installed
    apt:
      name: hddtemp
      state: present
  - name: Configure /etc/default/hddtemp
    copy:
      src: files/hddtemp
      dest: /etc/default/hddtemp
      owner: root
      group: root
      mode: 0644
    notify: Restart hddtemp 
  - name: Check if hddtemp is enabled and running
    ansible.builtin.systemd:
      name: hddtemp
      state: started
      enabled: yes
  handlers:
  - name: Restart hddtemp
    service:
      name: hddtemp.service
      state: restarted

