---
- hosts: all
  become: yes
  become_user: root
  tasks:
  - name: logrotate - Check if installed
    apt:
      name: logrotate
      state: present
  - name: logrotate - Configure service
    copy:
      src: files/logrotate.conf
      dest: /etc/logrotate.conf
      owner: root
      group: root
      mode: 0644
    notify: Restart logrotate
  - name: logrotate - Configure logrotate for postfix
    copy:
      src: files/logrotate-postfix.conf
      dest: /etc/logrotate.d/postfix-remote
      owner: root
      group: root
      mode: 0644
    notify: logrotate - Restart
  handlers:
  - name: logrotate - Restart
    service:
      name: logrotate.timer
      state: restarted

