---
- hosts: all
  become: yes
  become_user: root
  tasks:
  - name: Check if base packages are installed
    apt:
      name: libbz2-dev, libreadline-dev, libsqlite3-dev, python3, python3-pip
      state: present
  - name: Update pyenv
    git:
      repo: 'https://github.com/pyenv/pyenv.git'
      dest: ~/.pyenv
      update: yes

