---
- hosts: all
  become: yes
  become_user: root
  tasks:
  - name: ruby - Ensure ruby from apt is not present
    apt:
      name: ruby
      state: absent
      update_cache: true
  - name: ruby - Install libffi and libyaml development packages
    apt:
      name: libffi-dev, libyaml-dev
      state: present
      update_cache: true

- hosts: all
  tasks:
  - name: ruby - Install rbenv
    command: curl -fsSL https://github.com/rbenv/rbenv-installer/raw/HEAD/bin/rbenv-installer | bash
    args:
      creates: ~/.rbenv

