---
- hosts: all
  become: yes
  become_user: root
  tasks:
  - name: syslog-ng - Ensure rsyslog is absent
    apt:
      name: rsyslog
      state: absent
  - name: syslog-ng - Check if installed
    apt:
      name: syslog-ng
      state: present
  - name: syslog-ng - Configure service
    copy:
      src: files/syslog-ng.conf
      dest: /etc/syslog-ng/syslog-ng.conf
      owner: root
      group: root
      mode: 0644
    notify: Reload syslog-ng
  - name: syslog-ng - Configure logrotate for service
    copy:
      src: files/logrotate-syslog-ng.conf
      dest: /etc/logrotate.d/syslog-ng-remote
      owner: root
      group: root
      mode: 0644
    notify: Reload syslog-ng
  handlers:
  - name: syslog-ng - Reload service
    service:
      name: syslog-ng
      state: reloaded
