---
- hosts: all
  become: yes
  become_user: root
  tasks:
  - name: Check if rsyslog is installed
    pacman:
      name: rsyslog
      state: absent
  - name: Check if syslog-ng is installed
    pacman:
      name: syslog-ng
      state: installed
  - name: Configure syslog-ng
    copy:
      src: files/syslog-ng.conf
      dest: /etc/syslog-ng/syslog-ng.conf
      owner: root
      group: root
      mode: 0644
  - name: Configure syslog-ng - logrotate
    copy:
      src: files/logrotate-syslog-ng.conf
      dest: /etc/logrotate.d/syslog-ng
      owner: root
      group: root
      mode: 0644
  - name: Reload syslog-ng
    service:
      name: syslog-ng@default
      state: reloaded
