---
- hosts: all
  become: yes
  become_user: root
  tasks:
  - name: Check if zsh is installed
    pacman:
      name: zsh
      state: installed
  - name: Configure zshrc
    copy:
      src: files/zshrc
      dest: ~/.zshrc
      owner: root
      group: root
      mode: 0600
  - name: Clone oh-my-zsh git repository
    git:
      repo: 'https://github.com/robbyrussell/oh-my-zsh.git'
      dest: /opt/oh-my-zsh
  - name: Configure oh-my-zsh
    file:
      src: /opt/oh-my-zsh
      dest: /root/.oh-my-zsh
      state: link
  - name: Clone fzf git repository
    git:
      repo: 'https://github.com/junegunn/fzf.git'
      version: 6c0fd7f9ca663f2057a114f1aa86bfe5f6a78c68
      dest: /opt/fzf
  - name: Configure fzf
    file:
      src: /opt/fzf
      dest: /root/.fzf
      state: link

# TODO: Add .oh-my-zsh, .fzf and .rbenv (on a gem playbook)
