---
- hosts: all
  become: yes
  become_user: root
  tasks:
  - name: Check if zsh is installed
    pacman:
      name: zsh
      state: installed
  - name: Configure zshrc for root
    copy:
      src: files/zshrc
      dest: ~/.zshrc
      mode: 0600
  - name: Configure oh-my-zsh for root
    git:
      repo: 'https://github.com/robbyrussell/oh-my-zsh.git'
      dest: /root/.oh-my-zsh
  - name: Configure fzf for root
    git:
      repo: 'https://github.com/junegunn/fzf.git'
      dest: /root/.fzf
- hosts: all
  tasks:
    - name: Configure zshrc for user
      copy:
        src: files/zshrc
        dest: ~/.zshrc
    - name: Configure oh-my-zsh for user
      git:
        repo: 'https://github.com/robbyrussell/oh-my-zsh.git'
        dest: ~/.oh-my-zsh
    - name: Configure fzf for user
      git:
        repo: 'https://github.com/junegunn/fzf.git'
        dest: ~/.fzf
