---
- hosts: all
  become: yes
  become_user: root
  tasks:
  - name: Check if zsh is installed
    pacman:
      name: zsh
      state: installed
  - name: Configure zshrc
    copy:
      src: files/zshrc
      dest: ~/.zshrc
      owner: root
      group: root
      mode: 0600
  - name: Clone oh-my-zsh git repository
    git:
      repo: 'https://github.com/robbyrussell/oh-my-zsh.git'
      version: master
      dest: ~/.oh-my-zsh
  - name: Clone fzf git repository
    git:
      repo: 'https://github.com/junegunn/fzf.git'
      version: master
      dest: ~/.fzf

# TODO: Add .oh-my-zsh, .fzf and .rbenv (on a gem playbook)
