# File managed by Ansible - https://github.com/pedbarbosa/ansible

LoadPlugin processes

<Plugin "processes">
  Process "apache2"
  Process "collectd"
  Process "dockerd"
  Process "docker-proxy"
  Process "httpd"
  Process "jellyfin"
  Process "kodi-x11"
  Process "mariadbd"
  Process "mergerfs"
  Process "mosquitto"
  Process "nginx"
  Process "Prowlarr"
  Process "python3"
  Process "Radarr"
  Process "rtorrent"
  Process "smbd"
  Process "smokeping"
  Process "sshd"
  Process "syncthing"
  Process "vaultwarden"
</Plugin>
