---
- hosts: openwrt
  gather_facts: false
  pre_tasks:
    - name: openwrt - Update apk package lists
      community.openwrt.apk:
        name: apk
        update_cache: true
  roles:
    - community.openwrt.init
  tasks:
    - name: openwrt - Install packages
      community.openwrt.apk:
        name: "{{ openwrt_packages | join(',') }}"
        state: present

    - name: openwrt - Restart uhttpd
      community.openwrt.service:
        name: uhttpd
        state: restarted
