---
- hosts: all
  become: yes
  become_user: root
  tasks:
  # - name: Update Pacman repositories
  #   pacman:
  #     update_cache: yes
  - name: Update Arch mirrorlist
    copy:
      src: files/mirrorlist
      dest: /etc/pacman.d/mirrorlist
      owner: root
      group: root
      mode: 0644
  - name: Check if base packages are installed
    pacman:
      name: autofs, bash-completion, bind-tools, cifs-utils, curl, dhcpcd, ethtool, git, iftop, iotop, lsof, mlocate, ncdu, net-tools, rsync, ruby, samba, sysstat, wget
      state: installed
  - name: Update bashrc
    copy:
      src: files/bash.bashrc
      dest: /etc/bash.bashrc
      owner: root
      group: root
      mode: 0644

