---
- hosts: all
  become: yes
  become_user: root
  tasks:
  - name: Check if collectd is installed
    apt:
      name: collectd
      state: present
  - name: Read secrets from file
    include_vars:
      file: ../secrets.yml
  - name: Configure collectd
    template:
      src: files/ubuntu.collectd.conf
      dest: /etc/collectd/collectd.conf
    notify: Restart collectd
  - name: Configure collectd df module
    template:
      src: files/collectd.d/df.conf
      dest: /etc/collectd/collectd.conf.d
    notify: Restart collectd
  - name: Configure collectd disk module
    template:
      src: files/collectd.d/disk.conf
      dest: /etc/collectd/collectd.conf.d
    notify: Restart collectd
  - name: Configure collectd interface module
    template:
      src: files/collectd.d/interface.conf
      dest: /etc/collectd/collectd.conf.d
    notify: Restart collectd
  - name: Configure collectd logfile module
    template:
      src: files/collectd.d/logfile.conf
      dest: /etc/collectd/collectd.conf.d
    notify: Restart collectd
  - name: Configure collectd ping module
    template:
      src: files/collectd.d/ping.conf
      dest: /etc/collectd/collectd.conf.d
    notify: Restart collectd
  - name: Configure collectd rrdtool module
    template:
      src: files/collectd.d/rrdtool.conf
      dest: /etc/collectd/collectd.conf.d
    notify: Restart collectd
  - name: Configure collectd sensors module
    template:
      src: files/collectd.d/sensors.conf
      dest: /etc/collectd/collectd.conf.d
    notify: Restart collectd
  - name: Configure collectd unixsock module
    template:
      src: files/collectd.d/unixsock.conf
      dest: /etc/collectd/collectd.conf.d
    notify: Restart collectd
  handlers:
  - name: Restart collectd 
    service:
      name: collectd
      state: restarted

