# File managed by Ansible - https://github.com/pedbarbosa/ansible

config adblock 'global'
	option adb_enabled '1'
	option adb_debug '1'
	option adb_safesearch '0'
	option adb_report '1'
	option adb_dns 'dnsmasq'
	option adb_repiface 'br-lan'
	option adb_mail '1'
	option adb_mailreceiver 'admin@{{ domain }}'
	option adb_mailsender 'router@{{ domain }}'
	option adb_fetchinsecure '1'
	option adb_mailprofile 'default'
	option adb_dnsforce '1'
	option adb_fetchcmd 'uclient-fetch'
	option adb_nicelimit '0'
	option adb_represolve '1'
	list adb_feed 'adaway'
	list adb_feed 'adguard'
	list adb_feed 'adguard_tracking'
	list adb_feed 'andryou'
	list adb_feed 'bitcoin'
	list adb_feed 'disconnect'
	list adb_feed 'doh_blocklist'
	list adb_feed 'hagezi'
	list adb_feed 'smarttv_tracking'
	list adb_feed 'winspy'
	list adb_feed 'yoyo'
	list adb_zonelist 'iot'
	list adb_zonelist 'lan'
