# File managed by Ansible - https://github.com/pedbarbosa/ansible

config globals 'globals'
	option alt_config_file "/etc/collectd.conf"
	option Interval '10'
{% if 'conntrack' in openwrt_collectd_plugins %}
config plugin 'conntrack'
	option enable '1'
{% endif %}
config plugin 'cpu'
	option enable '1'
config plugin 'df'
	option enable '1'
	list FSType 'tmpfs'
	option IgnoreSelected '1'
{% if 'dns' in openwrt_collectd_plugins %}
config plugin 'dns'
	option enable '1'
{% for iface in openwrt_collectd_dns_interfaces %}
	list Interface '{{ iface }}'
{% endfor %}
{% endif %}
config plugin 'interface'
	option enable '1'
	list Interface 'lo'
	option IgnoreSelected '1'
config plugin 'iwinfo'
	option enable '1'
config plugin 'load'
	option enable '1'
config plugin 'memory'
	option enable '1'
config plugin 'network'
	option enable '1'
config network_server
	option host '{{ openwrt_collectd_server_host }}'
	option port '{{ openwrt_collectd_server_port }}'
config plugin 'processes'
	option enable '1'
{% for proc in openwrt_collectd_processes %}
	list Process '{{ proc }}'
{% endfor %}
{% if 'thermal' in openwrt_collectd_plugins %}
config plugin 'thermal'
	option enable '1'
	option IgnoreSelected '1'
{% for dev in openwrt_collectd_thermal_devices %}
	list Device '{{ dev }}'
{% endfor %}
{% endif %}
config plugin 'uptime'
	option enable '1'
