# File managed by Ansible - https://github.com/pedbarbosa/ansible

config dnsmasq
	option domainneeded '1'
	option localise_queries '1'
	option rebind_protection '1'
	option rebind_localhost '1'
	option local '/lan/'
	option domain '{{ domain }}'
	option expandhosts '1'
	option cachesize '1000'
{% if 'router' in group_names %}
	option authoritative '1'
{% endif %}
	option readethers '1'
	option leasefile '/tmp/dhcp.leases'
	option resolvfile '/tmp/resolv.conf.d/resolv.conf.auto'
	option localservice '1'
	option ednspacket_max '1232'
	option filter_aaaa '1'
{% if 'router' in group_names %}
	option sequential_ip '1'
	option nonegcache '1'
{% else %}
	list server '{{ openwrt_router_host }}'
{% endif %}

{% if 'router' in group_names %}
config dhcp 'lan'
	option interface 'lan'
	option start '100'
	option limit '150'
	option leasetime '1h'
	option dhcpv4 'server'
	option force '1'
	option ra 'disabled'
	option dhcpv6 'disabled'

config dhcp 'iot'
	option interface 'iot'
	option start '100'
	option limit '100'
	option leasetime '1h'
	option dhcpv4 'server'
	option force '1'
	option ra 'disabled'
	option dhcpv6 'disabled'

config dhcp 'wan'
	option interface 'wan'
	option ignore '1'
{% else %}
config dhcp 'lan'
	option interface 'lan'
	option ignore '1'
	option master '1'
	option ra 'server'
	option dhcpv6 'server'
	option dhcpv4 'server'
	option ra_slaac '1'
	list ra_flags 'managed-config'
	list ra_flags 'other-config'
{% endif %}

config odhcpd 'odhcpd'
	option maindhcp '0'
	option leasefile '/tmp/hosts/odhcpd'
	option leasetrigger '/usr/sbin/odhcpd-update'
	option loglevel '4'
	option piofolder '/tmp/odhcpd-piofolder'
{% if 'router' in group_names and openwrt_router_dhcp_extra | default('') %}

{{ openwrt_router_dhcp_extra }}
{%- endif %}
