# File managed by Ansible - https://github.com/pedbarbosa/ansible

{% if 'router' in group_names %}
{{ openwrt_router_firewall_config }}
{%- else %}
config defaults
	option input 'ACCEPT'
	option output 'ACCEPT'
	option forward 'ACCEPT'
	option synflood_protect '0'
	option flow_offloading '1'
	option flow_offloading_hw '1'

config zone
	option name 'lan'
	list network 'lan'
	list network 'iot'
	option input 'ACCEPT'
	option output 'ACCEPT'
	option forward 'ACCEPT'
{%- endif %}
