config interface 'loopback'
	option device 'lo'
	option proto 'static'
	option ipaddr '127.0.0.1'
	option netmask '255.0.0.0'

config globals 'globals'
	option packet_steering '2'

config device
	option name 'br-lan'
	option type 'bridge'
	option vlan_filtering '1'
	option ipv6 '0'
	list ports 'eth0'

config bridge-vlan
	option device 'br-lan'
	option vlan '10'
	list ports 'eth0:u*'

config bridge-vlan
	option device 'br-lan'
	option vlan '20'
	list ports 'eth0:t'

config interface 'lan'
	option proto 'static'
	option ipaddr '{{ ansible_host }}'
	option netmask '255.255.255.0'
	option gateway '{{ openwrt_router_host }}'
	option device 'br-lan.10'
	option delegate '0'
	list dns '{{ openwrt_router_host }}'

config interface 'iot'
	option device 'br-lan.20'
	option proto 'none'
	option delegate '0'
