config interface 'loopback'
	option device 'lo'
	option proto 'static'
	option ipaddr '127.0.0.1'
	option netmask '255.0.0.0'

config globals 'globals'
	option packet_steering '2'

config interface 'lan'
	option device 'br-lan.10'
	option proto 'static'
	option ipaddr '{{ ansible_host }}'
	option netmask '255.255.255.0'
	option gateway '{{ openwrt_router_host }}'
	option delegate '0'
	list dns '{{ openwrt_router_host }}'

config device 'br_lan'
	option name 'br-lan'
	option type 'bridge'
	option vlan_filtering '1'
	option ipv6 '0'
	list ports 'lan2'
	list ports 'lan3'
	list ports 'lan4'
	list ports 'wan'

config bridge-vlan
	option device 'br-lan'
	option vlan '10'
	list ports 'lan2:u*'
	list ports 'lan3:u*'
	list ports 'lan4:u*'
	list ports 'wan:u*'

config bridge-vlan
	option device 'br-lan'
	option vlan '20'
	list ports 'lan2:t'
	list ports 'lan3:t'
	list ports 'lan4:t'
	list ports 'wan:t'

config interface 'iot'
	option device 'br-lan.20'
	option proto 'none'
	option delegate '0'
