# File managed by Ansible - https://github.com/pedbarbosa/ansible

config interface 'loopback'
	option device 'lo'
	option proto 'static'
	option ipaddr '127.0.0.1'
	option netmask '255.0.0.0'

config globals 'globals'
	option packet_steering '2'

config device
	option name 'br-lan'
	option type 'bridge'
	option ipv6 '0'
	option vlan_filtering '1'
	list ports 'lan1'
	list ports 'lan2'
	list ports 'lan3'
	list ports 'lan4'
	list ports 'lan5'

config bridge-vlan
	option device 'br-lan'
	option vlan '10'
	list ports 'lan1:u*'
	list ports 'lan2:u*'
	list ports 'lan3:u*'
	list ports 'lan4:u*'
	list ports 'lan5:u*'

config bridge-vlan
	option device 'br-lan'
	option vlan '20'
	list ports 'lan1:t'
	list ports 'lan2:t'
	list ports 'lan3:t'
	list ports 'lan4:t'
	list ports 'lan5:t'

config interface 'lan'
	option device 'br-lan.10'
	option proto 'static'
	option ipaddr '{{ ansible_host }}'
	option netmask '255.255.255.0'

config interface 'iot'
	option proto 'static'
	option device 'br-lan.20'
	option ipaddr '{{ openwrt_router_iot_host }}'
	option netmask '255.255.255.0'
	option delegate '0'

config interface 'wan'
	option device 'eth1'
	option proto 'pppoe'
	option username '{{ openwrt_wan_pppoe_username }}'
	option password '{{ openwrt_wan_pppoe_password }}'
	option ipv6 '0'
	option peerdns '0'
{% for server in openwrt_wan_dns_servers %}
	list dns '{{ server }}'
{% endfor %}
