# File managed by Ansible - https://github.com/pedbarbosa/ansible

config system
	option hostname '{{ inventory_hostname }}'
	option timezone '{{ openwrt_timezone }}'
	option ttylogin '0'
{% if 'router' in group_names %}
	option log_file '/overlay/log/messages'
{% endif %}
	option log_size '{{ openwrt_log_size }}'
	option urandom_seed '0'
	option zonename '{{ openwrt_zonename }}'
	option log_proto 'udp'
	option conloglevel '8'
	option cronloglevel '{{ openwrt_cronloglevel }}'
	option log_ip '{{ openwrt_collectd_server_host }}'
	option log_port '{{ openwrt_log_port }}'
{% if 'router' in group_names %}
	option kernel_watchdog '1'
{% endif %}

{% if 'router' in group_names %}
config timeserver 'ntp'
{% for server in openwrt_ntp_pool_servers %}
	list server '{{ server }}'
{% endfor %}
	option enable_server '1'
	option interface 'lan'
{% else %}
config timeserver 'ntp'
	list server '{{ openwrt_router_host }}'
	option use_dhcp '0'
{% endif %}
{% for led in openwrt_leds %}

config led{{ " '" ~ led.section ~ "'" if led.section is defined else "" }}
	option name '{{ led.name }}'
	option sysfs '{{ led.sysfs }}'
	option trigger '{{ led.trigger }}'
{% if led.default is defined %}
	option default '{{ led.default }}'
{% endif %}
{% if led.mode is defined %}
	option mode '{{ led.mode }}'
{% endif %}
{% if led.dev is defined %}
	option dev '{{ led.dev }}'
{% endif %}
{% endfor %}
